# Generated by Django 4.1.7 on 2023-05-09 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryitem',
            name='description',
        ),
    ]
