# Generated by Django 4.1.7 on 2023-05-09 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_remove_categoryitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryitem',
            old_name='side_effect',
            new_name='side_effects',
        ),
    ]
