# Generated by Django 4.1.7 on 2023-05-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_rename_side_effect_categoryitem_side_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryitem',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
